// Auto-generated by scripts/update-branch-date.js - do not edit directly.
// Mirrors BranchVersion.json for pages opened via file:// (see comment there).
window.BRANCH_VERSION = {
  "date": "24-8-26",
  "branch": "Ethan-Dev-3.x.x",
  "version": "7.2.0-N",
  "colour": "main"
};
