// Auto-generated by scripts/update-branch-date.js — do not edit directly.
// Mirrors BranchVersion.json for pages opened via file:// (see comment there).
window.BRANCH_VERSION = {
  "date": "19-8-26",
  "branch": "Backend",
  "version": "7.0.0",
  "colour": "main"
};
