// Auto-generated by scripts/update-branch-date.js — do not edit directly.
// Mirrors BranchVersion.json for pages opened via file:// (see comment there).
window.BRANCH_VERSION = {
  "date": "14-8-26",
  "branch": "Devpanel",
  "version": "6.0.5",
  "colour": "main"
};
