[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/grade"
  to = "/.netlify/functions/grade"
  status = 200

[[redirects]]
  from = "/api/registerRole"
  to = "/.netlify/functions/registerRole"
  status = 200